### ISSUE TITLE
PDFNotImplementedError: Colorspace 'PDFObjRef:100>' is not supported

### ISSUE THREAD

**Issue by prabhatmishra33** [felipeochoa/minecart#23]
There are 2 images in the pdf which i am trying to read,
1st is the logo.
2nd is the handwritten Sign.

The library is able to read the logo and convert to image using pillow.
but the issue comes when it tries to read the  handwritten sign ,it spits out below error:
```
im = page.images[1].as_pil()
Traceback (most recent call last):

  File "<ipython-input-77-93f421217555>", line 1, in <module>
    im = page.images[1].as_pil()

  File "C:\Program Files\Anaconda3\lib\site-packages\minecart\content.py", line 363, in as_pil
    "Colorspace %r is not supported" % colorspace)

PDFNotImplementedError: Colorspace 'PDFObjRef:100>' is not supported
```
python version used : Python 3.5.2 :: Anaconda 4.2.0 (64-bit)

Thanks,
Prabhat

**Comment by mujeeb-merwat** [comment]
Prabhat I also face the same problem. Are you solved the error.?

**Comment by vgopinath** [comment]
Look at this issue for a fix:
https://github.com/felipeochoa/minecart/issues/16

This is an excellent library (just finding out)… Please continue develop, when I have some time, will contribute.
